In [1]:
import pandas as pd
import re

In [2]:
pd_data = pd.read_csv('../codes/data/product_data.csv')
pd_data_dropna = pd_data.dropna(subset=['Name'])
pd_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2988 entries, 0 to 3060
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 2988 non-null   object
 1   product_links         2988 non-null   object
 2   pd_id                 2988 non-null   object
 3   Name                  2988 non-null   object
 4   Description           2988 non-null   object
 5   AverageOverallRating  2988 non-null   float64
 6   FirstSubmissionTime   2988 non-null   object
 7   LastSubmissionTime    2988 non-null   object
 8   Age_35to44            2164 non-null   float64
 9   Age_18to24            2104 non-null   float64
 10  Age_25to34            2396 non-null   float64
 11  Age_45to54            1791 non-null   float64
 12  Age_over54            1986 non-null   float64
 13  Age_13to17            1375 non-null   float64
dtypes: float64(7), object(7)
memory usage: 350.2+ KB

In [3]:
pd_info = pd.read_csv('../codes/data/pd_info.csv')
pd_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3061 entries, 0 to 3060
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pd_id          3061 non-null   object
 1   size_and_item  2360 non-null   object
 2   category       2360 non-null   object
 3   price          2360 non-null   object
 4   love_count     2359 non-null   float64
 5   reviews_count  2328 non-null   float64
dtypes: float64(2), object(4)
memory usage: 143.6+ KB

In [4]:
pd_info_dropna = pd_info.dropna(subset=['pd_id', 'size_and_item', 'category'])
pd_info_fillna = pd_info_dropna.fillna(0)
pd_info_fillna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2360 entries, 2 to 3059
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pd_id          2360 non-null   object
 1   size_and_item  2360 non-null   object
 2   category       2360 non-null   object
 3   price          2360 non-null   object
 4   love_count     2360 non-null   float64
 5   reviews_count  2360 non-null   float64
dtypes: float64(2), object(4)
memory usage: 129.1+ KB

In [5]:
pd_whole = pd.merge(pd_data_dropna, pd_info_fillna, on='pd_id')
pd_whole.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2301 entries, 0 to 2300
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 2301 non-null   object
 1   product_links         2301 non-null   object
 2   pd_id                 2301 non-null   object
 3   Name                  2301 non-null   object
 4   Description           2301 non-null   object
 5   AverageOverallRating  2301 non-null   float64
 6   FirstSubmissionTime   2301 non-null   object
 7   LastSubmissionTime    2301 non-null   object
 8   Age_35to44            1661 non-null   float64
 9   Age_18to24            1620 non-null   float64
 10  Age_25to34            1852 non-null   float64
 11  Age_45to54            1382 non-null   float64
 12  Age_over54            1530 non-null   float64
 13  Age_13to17            1075 non-null   float64
 14  size_and_item         2301 non-null   object
 15  category              2301 non-null   object
 16  price                 2301 non-null   object
 17  love_count            2301 non-null   float64
 18  reviews_count         2301 non-null   float64
dtypes: float64(9), object(10)
memory usage: 359.5+ KB

In [6]:
pd_whole.sample(5)

,brand,product_links,pd_id,Name,Description,AverageOverallRating,FirstSubmissionTime,LastSubmissionTime,Age_35to44,Age_18to24,Age_25to34,Age_45to54,Age_over54,Age_13to17,size_and_item,category,price,love_count,reviews_count
262,bvlgari,https://www.sephora.com/product/eau-parfumee-a...,P0847,Eau Parfumée Au Thé Vert,Fragrance Family: FreshScent Type: Fresh Citru...,4.4392,2008-09-11T22:45:05.000+00:00,2020-06-14T04:35:46.000+00:00,25.0,13.0,31.0,24.0,20.0,2.0,SIZE 5 oz•ITEM 1747864,"Fragrance, Women, Perfume",$162.00,5868.0,148.0
2059,tan-luxe,https://www.sephora.com/product/super-glow-hya...,P447199,Super Glow Hyaluronic Self-Tan Serum,"What it is: A one-of-a-kind hyaluronic, superf...",4.1562,2019-07-01T21:20:27.000+00:00,2020-07-01T01:36:29.000+00:00,NaN,2.0,1.0,1.0,1.0,NaN,SIZE 1.01 oz/ 30 mL•ITEM 2256790,"Skincare, Self Tanners, For Face",$49.00,10072.0,97.0
503,dphue,https://www.sephora.com/product/color-boosting...,P409401,Gloss+ Semi-permanent Hair Color and Deep Cond...,What it is: A semi-permanent hair color in a d...,3.7940,2016-06-07T01:08:11.000+00:00,2020-07-03T23:37:53.000+00:00,13.0,6.0,16.0,4.0,5.0,1.0,SIZE 6.5 oz/ 192 mL•ITEM 2204592,"Hair, Hair Styling & Treatments, Scalp & Hair ...",$35.00,26722.0,268.0
2223,violet-voss,https://www.sephora.com/product/eye-glitter-to...,P437080,Eye Glitter Topper Infinity,What it is: A glitter topper with a shimmering...,4.5806,2018-10-10T23:37:34.000+00:00,2020-06-28T11:32:57.000+00:00,4.0,NaN,5.0,2.0,NaN,1.0,SIZE 0.13 oz/ 4 mL•ITEM 2156131,"Makeup, Eye, Eyeshadow",$15.00,18201.0,62.0
1670,pink-sugar,https://www.sephora.com/product/pink-sugar-sho...,P380594,Pink Sugar Shower Gel,"Stylish and lively, with a distinctive persona...",3.6667,2013-07-21T20:34:21.000+00:00,2016-09-17T17:11:38.000+00:00,NaN,NaN,NaN,NaN,NaN,NaN,SIZE 8.5 oz/ 250 mL•ITEM 698100,"Fragrance, Women, Bath & Shower",$20.00,790.0,3.0

From the sample dataframe and dataframe info, we can recognize that `Product_Id`, `item_num` and `link` may be not useful for analysis. Therefore, we are going to drop these three columns. Besides, `category` should be splited into three columns. `size` could have na value or other invalid value. Other columns like `love_count`, `rating`, `reviews_count` should turn to numeric variables.

# Let's start cleaning data!

## drop columns

In [7]:
raw_data_c = pd_whole.drop(columns=['product_links'])
raw_data_c.sample(5)

,brand,pd_id,Name,Description,AverageOverallRating,FirstSubmissionTime,LastSubmissionTime,Age_35to44,Age_18to24,Age_25to34,Age_45to54,Age_over54,Age_13to17,size_and_item,category,price,love_count,reviews_count
1051,kitsch,P453646,Kitsch x Justine Marjan Rhinestone Queen Bobby...,What it is: An elevated and effortless stateme...,3.0000,2020-01-18T01:41:22.000+00:00,2020-07-02T20:17:51.000+00:00,NaN,NaN,NaN,NaN,NaN,NaN,ITEM 2291359,"Hair, Hair Tools, Hair Accessories",$29.00 $20.00,2008.0,2.0
941,john-varvatos,P434203,JV x NJ John Varvatos Nick Jonas,Fragrance Family: Earthy & WoodyScent Type: Ci...,3.8333,2018-10-02T05:17:36.000+00:00,2020-06-15T21:09:58.000+00:00,1.0,NaN,NaN,NaN,1.0,NaN,SIZE 4.2 oz/ 125 mL•ITEM 2101921,"Fragrance, Men, Cologne",$94.00,452.0,6.0
970,juicy-couture,P387939,Viva La Juicy Gold Couture,Experience a couture overdose. The Viva la Jui...,4.6015,2014-07-11T03:08:53.000+00:00,2020-04-01T19:42:11.000+00:00,14.0,20.0,11.0,4.0,2.0,NaN,SIZE 1.7 oz/ 50 mL•ITEM 1641562,Fragrance,$79.00,8660.0,133.0
194,bkr,P422320,Spiked Lala Glass Water Bottle,"What it is:An opaque lavender, spiked, reusabl...",4.5686,2018-01-13T12:41:32.000+00:00,2020-07-05T17:33:33.000+00:00,2.0,1.0,2.0,1.0,1.0,1.0,SIZE 32 oz/ 1 L•ITEM 2003754,"Skincare, Wellness, Holistic Wellness",$58.00 $34.80,6377.0,52.0
1602,paco-rabanne,P445811,Invictus Legend,Fragrance Family: Earthy & WoodyScent Type: Wa...,5.0000,2019-07-26T00:55:50.000+00:00,2020-03-27T22:15:29.000+00:00,1.0,NaN,NaN,NaN,NaN,NaN,SIZE 3.4oz/100mL•ITEM 2175230,Fragrance,$100.00,660.0,8.0

## Price

In [8]:
raw_data_c[['AverageOverallRating', 'Age_13to17', 
            'Age_18to24', 'Age_25to34', 
            'Age_35to44', 'Age_45to54', 
            'Age_over54']] = raw_data_c[['AverageOverallRating', 'Age_13to17', 
                                         'Age_18to24', 'Age_25to34', 
                                         'Age_35to44', 'Age_45to54', 
                                         'Age_over54']].fillna(0)

In [9]:
raw_data_c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2301 entries, 0 to 2300
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 2301 non-null   object
 1   pd_id                 2301 non-null   object
 2   Name                  2301 non-null   object
 3   Description           2301 non-null   object
 4   AverageOverallRating  2301 non-null   float64
 5   FirstSubmissionTime   2301 non-null   object
 6   LastSubmissionTime    2301 non-null   object
 7   Age_35to44            2301 non-null   float64
 8   Age_18to24            2301 non-null   float64
 9   Age_25to34            2301 non-null   float64
 10  Age_45to54            2301 non-null   float64
 11  Age_over54            2301 non-null   float64
 12  Age_13to17            2301 non-null   float64
 13  size_and_item         2301 non-null   object
 14  category              2301 non-null   object
 15  price                 2301 non-null   object
 16  love_count            2301 non-null   float64
 17  reviews_count         2301 non-null   float64
dtypes: float64(9), object(9)
memory usage: 341.6+ KB

From the dataframe above, we can also observe that price may contain dollar sign as well. So we need to strip that.

In [10]:
# remove dollar sign for price column
special_price = raw_data_c['price']
special_price_sr = special_price.str.extractall(r"[$](?P<number>\d+)")
special_price_df = special_price_sr.reset_index().pivot(
    index='level_0', columns='match', values='number').reset_index()
special_price_df.columns = ['index', 'Price_0', 'Price_1', 'Price_2']
special_price_df[['Price_0', 'Price_1', 'Price_2']] = special_price_df[[
    'Price_0', 'Price_1', 'Price_2']].astype(float)

In [11]:
Price = special_price_df.drop(columns=['index']).max(axis=1)
Price.name = 'Price'

In [12]:
add_price_df = pd.concat([raw_data_c, Price], axis=1)
clean_price = add_price_df.drop(columns=['price'])
clean_price.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2301 entries, 0 to 2300
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 2301 non-null   object
 1   pd_id                 2301 non-null   object
 2   Name                  2301 non-null   object
 3   Description           2301 non-null   object
 4   AverageOverallRating  2301 non-null   float64
 5   FirstSubmissionTime   2301 non-null   object
 6   LastSubmissionTime    2301 non-null   object
 7   Age_35to44            2301 non-null   float64
 8   Age_18to24            2301 non-null   float64
 9   Age_25to34            2301 non-null   float64
 10  Age_45to54            2301 non-null   float64
 11  Age_over54            2301 non-null   float64
 12  Age_13to17            2301 non-null   float64
 13  size_and_item         2301 non-null   object
 14  category              2301 non-null   object
 15  love_count            2301 non-null   float64
 16  reviews_count         2301 non-null   float64
 17  Price                 2301 non-null   float64
dtypes: float64(10), object(8)
memory usage: 341.6+ KB

In [13]:
clean_price['FirstSubmissionTime'] = pd.to_datetime(clean_price['FirstSubmissionTime'], 
                                                    format='%Y-%m-%dT%H:%M:%S.000+00:00')
clean_price['LastSubmissionTime'] = pd.to_datetime(clean_price['LastSubmissionTime'], 
                                                    format='%Y-%m-%dT%H:%M:%S.000+00:00')
clean_price.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2301 entries, 0 to 2300
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 2301 non-null   object
 1   pd_id                 2301 non-null   object
 2   Name                  2301 non-null   object
 3   Description           2301 non-null   object
 4   AverageOverallRating  2301 non-null   float64
 5   FirstSubmissionTime   2301 non-null   datetime64[ns]
 6   LastSubmissionTime    2301 non-null   datetime64[ns]
 7   Age_35to44            2301 non-null   float64
 8   Age_18to24            2301 non-null   float64
 9   Age_25to34            2301 non-null   float64
 10  Age_45to54            2301 non-null   float64
 11  Age_over54            2301 non-null   float64
 12  Age_13to17            2301 non-null   float64
 13  size_and_item         2301 non-null   object
 14  category              2301 non-null   object
 15  love_count            2301 non-null   float64
 16  reviews_count         2301 non-null   float64
 17  Price                 2301 non-null   float64
dtypes: datetime64[ns](2), float64(10), object(6)
memory usage: 341.6+ KB

## split category into three columns

In [14]:
category_lst_series = clean_price['category'].str.split(',')
clean_price['category_1'] = category_lst_series.str[0]
clean_price['category_2'] = category_lst_series.str[1]
clean_price['category_3'] = category_lst_series.str[2]
clean_price.sample(5)

,brand,pd_id,Name,Description,AverageOverallRating,FirstSubmissionTime,LastSubmissionTime,Age_35to44,Age_18to24,Age_25to34,...,Age_over54,Age_13to17,size_and_item,category,love_count,reviews_count,Price,category_1,category_2,category_3
649,farsali,P425699,Unicorn Essence Antioxidant Primer Serum Mini,Which skin type is it good for? ✔ Normal ✔ Oil...,3.8030,2017-02-15 00:30:34,2020-07-02 20:31:36,21.0,55.0,72.0,...,19.0,7.0,ITEM 2001220,"Mini Size, Makeup",100373.0,1462.0,22.0,Mini Size,Makeup,NaN
1426,mugler,P424557,Alien Hair Mist,What it is: A luxurious hair mist to pamper an...,4.5000,2017-10-18 20:54:24,2020-01-01 10:16:41,0.0,0.0,2.0,...,0.0,0.0,SIZE 1.0 oz/ 30 mL•ITEM 1917384,Fragrance,4295.0,24.0,40.0,Fragrance,NaN,NaN
1620,patrick-ta,P456592,Major Brow Shaping Wax Clear,What it is: An innovative defining wax that wi...,3.5956,2020-04-20 18:52:44,2020-07-06 01:38:45,0.0,4.0,6.0,...,1.0,2.0,SIZE 0.17 oz/ 5 g•ITEM 2340263,Makeup,16255.0,138.0,22.0,Makeup,NaN,NaN
261,bvlgari,P455017,Rose Goldea Blossom Delight,Fragrance Family: FloralsScent Type: Classic F...,2.6667,2020-04-09 20:15:56,2020-05-06 16:53:18,0.0,0.0,1.0,...,0.0,0.0,SIZE 2.5 oz/ 75 mL•ITEM 2328334,Fragrance,786.0,3.0,114.0,Fragrance,NaN,NaN
2028,supergoop,P386793,CC Cream Daily Correct Broad Spectrum SPF 35 S...,"What it is: A 100 percent mineral, color-corre...",4.2415,2014-07-09 07:25:43,2020-07-07 03:48:26,9.0,13.0,30.0,...,8.0,2.0,SIZE 1.6 oz/ 47 mL•ITEM 1628767,Skincare,62580.0,830.0,36.0,Skincare,NaN,NaN

## Size

As there are different measure for different products. Here, we mainly focus on products that can be measured by 'ml', 'oz', and 'g'.

Use regex to find measures with oz or mL or g and create responding columns

In [15]:
def find_measure(measure, text):
    regex = '(\d?\.?\d+).?' + measure   
    result = re.findall(regex, text)
    if len(result)!=0:
        return result[0]
    else:
        return None

In [16]:
measures = [' oz', ' mL', ' g']
for measure in measures:
    measure_ = measure.split(' ')[-1]
    name = 'size_' + measure_
    clean_price[name] = clean_price.loc[(clean_price['size_and_item'].str.contains(measure_)) &
                                          (~clean_price['size_and_item'].str.contains('x')), 'size_and_item'].apply(lambda x: find_measure(measure_, x))
clean_price.sample(5)

,brand,pd_id,Name,Description,AverageOverallRating,FirstSubmissionTime,LastSubmissionTime,Age_35to44,Age_18to24,Age_25to34,...,category,love_count,reviews_count,Price,category_1,category_2,category_3,size_oz,size_mL,size_g
1798,rms-beauty,P442232,Luminizing & Bronzing Powders Madeira Bronzer,What it is: A multidimensional powder in three...,4.5526,2019-02-19 14:18:17,2020-06-21 19:26:15,1.0,2.0,0.0,...,"Makeup, Face, Setting Spray & Powder",8647.0,38.0,38.0,Makeup,Face,Setting Spray & Powder,0.52,NaN,15
413,clinique,P122912,High Impact Mascara,"What it is:A richly-pigmented, volumizing masc...",4.2883,2008-08-30 17:27:00,2020-07-05 04:45:08,244.0,552.0,640.0,...,"Makeup, Eye, Mascara",35738.0,2620.0,19.0,Makeup,Eye,Mascara,NaN,NaN,NaN
1555,omorovicza,P386798,Refining Facial Polisher,What it is:An effective skin polisher featurin...,4.7013,2014-05-13 16:17:46,2020-06-08 18:53:38,0.0,0.0,2.0,...,"Skincare, Cleansers, Exfoliators",5425.0,77.0,99.0,Skincare,Cleansers,Exfoliators,3.5,104,NaN
1498,nest,P457258,Mini Sunkissed Perfume & Glow Set,Fragrance Family: FloralsScent Type: Warm Flor...,4.5294,2020-04-22 03:42:34,2020-06-25 17:59:28,3.0,0.0,3.0,...,"Fragrance, Value & Gift Sets, Perfume Gift Sets",3036.0,17.0,22.0,Fragrance,Value & Gift Sets,Perfume Gift Sets,NaN,NaN,NaN
62,the-art-of-shaving,P225361,The 4 Elements of the Perfect Shave™ - Sandalwood,What it is:A luxurious quartet of shaving esse...,4.8462,2008-12-26 17:21:57,2020-05-06 18:41:03,2.0,5.0,20.0,...,"Men, Value & Gift Sets, Skincare Sets",2281.0,39.0,137.0,Men,Value & Gift Sets,Skincare Sets,NaN,NaN,NaN

In [17]:
clean_df = clean_price.drop(columns=['size_and_item'])
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2301 entries, 0 to 2300
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   brand                 2301 non-null   object
 1   pd_id                 2301 non-null   object
 2   Name                  2301 non-null   object
 3   Description           2301 non-null   object
 4   AverageOverallRating  2301 non-null   float64
 5   FirstSubmissionTime   2301 non-null   datetime64[ns]
 6   LastSubmissionTime    2301 non-null   datetime64[ns]
 7   Age_35to44            2301 non-null   float64
 8   Age_18to24            2301 non-null   float64
 9   Age_25to34            2301 non-null   float64
 10  Age_45to54            2301 non-null   float64
 11  Age_over54            2301 non-null   float64
 12  Age_13to17            2301 non-null   float64
 13  category              2301 non-null   object
 14  love_count            2301 non-null   float64
 15  reviews_count         2301 non-null   float64
 16  Price                 2301 non-null   float64
 17  category_1            2301 non-null   object
 18  category_2            1765 non-null   object
 19  category_3            1598 non-null   object
 20  size_oz               1378 non-null   object
 21  size_mL               1034 non-null   object
 22  size_g                254 non-null    object
dtypes: datetime64[ns](2), float64(10), object(11)
memory usage: 431.4+ KB

In [18]:
clean_df.to_csv('cleaned_pd_data.csv', index=False)